### PR TITLE
Add missing parts of index.html

### LINKED ISSUE #6: index.html is missing a bunch of stuff
List of things missing from `index.html` file:

- Closing tag for `<html>`
- `<head>` tags
- `<body>` tags
- Responsive `<meta>` tag

The file also needs to be formatted as it has no indentation whatsoever right now.

### PR DESCRIPTION
**Pull request by andria-dev**
Fixes #6

- ~Adds closing `<html>` tag~
- ~Adds `<head>` and `<body>` tags~
- Adds responsive `<meta>` tag
- Changes title to "Haunted App"
- ~Adds indentation~

### CODE REVIEW

**Comment by matthewp** [comment]
I want to stick with my style of not having head and body tags, and not having a closing HTML tag, I'm sorry. I know it's unusual but I think once you get used to it it reduces the amount of noise. Every tag used matters.

**Comment by andria-dev** [comment]
Okay, I'll modify the commits here pretty soon to reflect that

**Comment by andria-dev** [comment]
@matthewp Fixed it 👍

**Comment by matthewp** [comment]
Would you mind removing the indentation?

**Comment by andria-dev** [comment]
Done 👍

**Comment by matthewp** [comment]
Thank you so much for staying with me, you're a rock star 🎸

**Pull request merged**
